name: SimpleTrade
version: ${project.version}
main: com.zayatv.simpletrade.SimpleTrade
api-version: 1.20
author: ZayaTV
description: Trade Plugin
softdepend:
  - Vault
permissions:
  simpletrade.*:
    description: ""
  simpletrade.trade:
    description: ""
commands:
  trade:
    description: ""